spring:
  application:
    name: netbanking-api-gateway
  cloud:
    gateway:
      routes:
        - id: netbanking-user-service
          uri: lb://netbanking-user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: netbanking-fund-transfer-service
          uri: lb://netbanking-fund-transfer-service
          predicates:
            - Path=/fund-transfer/**
          filters:
            - StripPrefix=1

        - id: core-banking-service
          uri: lb://core-banking-service
          predicates:
            - Path=/banking-core/**
          filters:
            - StripPrefix=1
        - id: netbanking-utility-payment-service
          uri: lb://netbanking-utility-payment-service
          predicates:
            - Path=/utility-payment/**
          filters:
            - StripPrefix=1

server:
  port: 8082

logging:
  level:
    org.springframework.cloud.gateway: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
