server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sahil-14/netbanking-config-server.git
          search-paths: configuration
          default-label: main
